### ISSUE TITLE
这个插件能直接置于浏览器窗口的底部吗？

### ISSUE THREAD

**Issue by whiteS18** [HerbertHe/docsify-beian#1]
谢谢作者提供的插件，但是我遇到一个问题：当我某一个md文件内容不够一页的时候，备案信息会紧跟着文章后面而不是窗口最下面。
![图片](https://user-images.githubusercontent.com/31566522/150481795-a2a4a1b1-f7ef-4ef5-ae3e-c9693701c0fe.png)
我该怎么把他放到红色方框的位置呢？

**Comment by HerbertHe** [comment]
你可以通过自行覆盖样式实现，因为插件的渲染机制设计就是这样。跟他们前后翻页设计的思路是一样的，紧跟着文档内容后面进行渲染，以规避可能的多插件渲染冲突问题。
